routes/web.php
<?php

use App\Http\Controllers\Dashboard\CompanyController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::middleware('is-admin')->group(function () {
    Route::resource('/companies', CompanyController::class);



    Route::resource('/employees', EmployeeController::class);

});

app/Models/Company.php
<?php

namespace App\Models;

use App\Domain\Company\Contracts\CompanyContract;
use App\Traits\SetImageStandard;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property string $email,
 * @property string $name,
 * @property string $site;
 * @property string $logo;
 */
class Company extends Model
{
    use HasFactory, SoftDeletes, SetImageStandard;

    protected $fillable = CompanyContract::FILLABLE;
}

app/Models/Employee.php
<?php

namespace App\Models;

use App\Domain\Employee\Contracts\EmployeeContract;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property string $name
 * @property string $surname
 * @property Company $company
 * @property string $email
 * @property string $phone
 **/

class Employee extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = EmployeeContract::FILLABLE;

    public function company()
    {
        return $this->belongsTo(Company::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use App\Domain\User\Contracts\UserContract;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;


/**
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property bool $is_admin
 */

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = UserContract::FILLABLE;

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function setPasswordAttribute($value)
    {
        $this->attributes[UserContract::PASSWORD] = Hash::make($value);
    }

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Dashboard/CompanyController.php
<?php

namespace App\Http\Controllers\Dashboard;


use App\Domain\Company\Contracts\CompanyRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyRequest;
use App\Http\Requests\CompanyUpdateRequest;
use App\Models\Company;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\View\View;

class CompanyController extends Controller
{

    public function __construct(
        protected CompanyRepositoryInterface $companyRepository
    )
    {

    }

    public function index(): View
    {
        return view('companies.index', [
            'companies' => $this->companyRepository->index()
        ]);
    }


    public function create(): View
    {
        return view('companies.create');
    }


    public function store(CompanyRequest $request): RedirectResponse
    {
        $this->companyRepository->create($request);

        return redirect()->route('companies.index');
    }


    public function show(Company $company): View
    {
        return view('companies.show', ['company' => $company]);
    }


    public function edit(Company $company): View
    {
        return view('companies.update', [
            'company' => $company
        ]);
    }


    public function update(CompanyUpdateRequest $request, Company $company) : RedirectResponse
    {
        $this->companyRepository->update($company, $request);

        return redirect()->route('companies.index');
    }


    public function destroy(Company $company) : RedirectResponse
    {
        $this->companyRepository->delete($company);


        return redirect()->route('companies.index');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Domain\Company\Contracts\CompanyRepositoryInterface;
use App\Domain\Employee\Contracts\EmployeeRepositoryInterface;
use App\Http\Requests\EmployeeStoreRequest;
use App\Http\Requests\EmployeeUpdateRequest;
use App\Models\Employee;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class EmployeeController extends Controller
{

    public function __construct(
        public EmployeeRepositoryInterface $employeeRepository,
        public CompanyRepositoryInterface  $companyRepository
    )
    {

    }

    public function index(): View
    {
        return view('employees.index', [
            'employees' => $this->employeeRepository->index(),
        ]);
    }


    public function create(): View
    {
        return view('employees.create', [
            'companies' => $this->companyRepository->index(),
        ]);
    }


    public function store(EmployeeStoreRequest $request): RedirectResponse
    {
        $this->employeeRepository->create($request);

        return redirect()->route('employees.index');
    }


    public function show(Employee $employee): View
    {
        return view('employees.show', [
            'employee' => $employee
        ]);
    }


    public function edit(Employee $employee): View
    {
        return view('employees.update', [
            'employee' => $employee,
            'companies' => $this->companyRepository->index()
        ]);
    }


    public function update(EmployeeUpdateRequest $request, Employee $employee): RedirectResponse
    {
        $this->employeeRepository->update($employee, $request);

        return redirect()->route('employees.index');
    }

    public function destroy(Employee $employee): RedirectResponse
    {
        $this->employeeRepository->delete($employee);

        return redirect()->route('employees.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a href="{{route('companies.index')}}" class="btn-primary btn">
                            {{__('Back')}}
                        </a>
                    </div>

                    <div class="card-body">
                        <form action="{{route('companies.store')}}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group mb-2">
                                <label for="name">{{__('Name')}}</label>
                                <input type="text" class="form-control" name="name" id="name" required>
                            </div>
                            <div class="form-group mb-2">
                                <label for="email">{{__('Email')}}</label>
                                <input type="text" class="form-control" name="email" id="email">
                            </div>
                            <div class="form-group mb-2">
                                <label for="site">{{__('Site')}}</label>
                                <input type="text" class="form-control" name="site" id="site">
                            </div>

                            <div class="form-group mb-2">
                                <label for="logo">{{__('Logo')}}</label>
                                <input type="file" class="form-control" name="logo" id="logo"
                                       accept="image/png, image/jpeg image/png" required>
                            </div>
                            <div class="form-group-mb-2">
                                <button type="submit" class="btn btn-primary">
                                    {{__('Submit')}}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <a href="{{route('home')}}" class="btn btn-primary "
                               style="margin-right: 20px;">{{__('Back')}}</a>

                            <h5>
                                {{__('Companies')}}
                            </h5>
                        </div>
                        <a href="{{route('companies.create')}}" class="btn btn-primary">
                            {{__('Create company')}}
                        </a>
                    </div>
                    <div class="card-body">
                        @foreach($companies as $company)
                            <div class="d-flex align-items-center">
                                <div class="w-25">
                                    <img src="{{$company->logo}}" width="50px" height="50px" class="" alt="">
                                </div>
                                <div class="w-50 ">
                                    {{$company->name}}
                                </div>

                                <div class="w-25 justify-content-between">
                                    <a href="{{route('companies.show',['company' => $company->id])}}"
                                       class="btn btn-primary">
                                        {{__('Show')}}
                                    </a>

                                    <a href="{{route('companies.edit',['company' => $company->id])}}"
                                       class="btn btn-primary">
                                        {{__('Edit')}}
                                    </a>

                                    <form action="{{route('companies.destroy',['company' => $company->id])}}"
                                          method="POST">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit"
                                           class="btn btn-primary mb-2 mt-2">
                                            {{__('Delete')}}
                                        </button>
                                    </form>
                                </div>


                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a href="{{route('companies.index')}}" class="btn btn-primary">Back</a>
                    </div>
                    <div class="card-body">
                        <div class="">
                            <img src="{{$company->logo}}" width="100px" alt="">
                        </div>
                        <div class="mt-5">
                            <h4>{{$company->name}}</h4>
                        </div>
                        <div class="mt-1">
                            Email : <a href="mailto:{{$company->email}}">{{$company->email}}</a>
                        </div>
                        <div class="mt-1">
                            Site: <a href="{{$company->site}}">{{$company->site}}</a>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/update.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <a href="{{route('companies.index')}}" class="btn-primary btn">
                            {{__('Back')}}
                        </a>
                    </div>

                    <div class="card-body">
                        <form action="{{route('companies.update',['company' => $company])}}" method="POST"
                              enctype="multipart/form-data">
                            @csrf
                            <input type="hidden" name="_method" value="put" />

                            <div class="form-group mb-2">
                                <label for="name">{{__('Name')}}</label>
                                <input type="text" class="form-control" name="name" id="name" required
                                       value="{{$company->name}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="email">{{__('Email')}}</label>
                                <input type="text" class="form-control" name="email" id="email"
                                       value="{{$company->email}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="site">{{__('Site')}}</label>
                                <input type="text" class="form-control" name="site" id="site"
                                       value="{{$company->site}}">
                            </div>

                            <div class="form-group mb-2">
                                <label for="logo">{{__('Logo')}}</label>
                                <input type="file" class="form-control" name="logo" id="logo"
                                       accept="image/png, image/jpeg image/png" required>
                            </div>
                            <div class="form-group-mb-2">
                                <button type="submit" class="btn btn-primary">
                                    {{__('Submit')}}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <a href="{{route('employees.index')}}" class="btn btn-primary " style="margin-right: 20px;">{{__('Back')}}</a>

                            <h5>
                                {{__('Employees')}}
                            </h5>
                        </div>

                    </div>
                    <div class="card-body">

                        <form action="{{route('employees.store')}}" method="POST">
                            @csrf
                            <div class="form-group mb-2">
                                <label for="name">{{__('Name')}}</label>
                                <input type="text" class="form-control" name="name" id="name" required>
                            </div>
                            <div class="form-group mb-2">
                                <label for="surname">{{__('Surname')}}</label>
                                <input type="text" class="form-control" name="surname" id="surname" required>
                            </div>
                            <div class="form-group mb-2">
                                <label for="email">{{__('Email')}}</label>
                                <input type="text" class="form-control" name="email" id="email">
                            </div>
                            <div class="form-group mb-2">
                                <label for="phone">{{__('Phone')}}</label>
                                <input type="tel" class="form-control" name="phone" id="phone">
                            </div>

                            <div class="form-group mb-2">
                                <label for="company">{{__('Company')}}</label>
                                <select name="company_id" id="company" class="form-control" required>

                                    @foreach($companies as $company)
                                        <option value="{{$company->id}}">{{$company->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group-mb-2">
                                <button type="submit" class="btn btn-primary">
                                    {{__('Submit')}}
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <a href="{{route('home')}}" class="btn btn-primary "
                               style="margin-right: 20px;">{{__('Back')}}</a>

                            <h5>
                                {{__('Employees')}}
                            </h5>
                        </div>
                        <a href="{{route('employees.create')}}" class="btn btn-primary">
                            {{__('Create employees')}}
                        </a>
                    </div>
                    <div class="card-body">
                        @foreach($employees as $employee)
                            <div class="d-flex align-items-center mb-2">
                                <div class="w-25">
                                    {{$employee->name}} {{$employee->surname}}
                                </div>
                                <div class="w-25">
                                    {{$employee->email}}
                                </div>
                                <div class="w-25">
                                    <a href="tel:{{$employee->phone}}">
                                        {{$employee->phone}}
                                    </a>
                                </div>
                                <div class="w-25">
                                    {{$employee->company->name}}
                                </div>
                                <div class="w-25">
                                    <a href="{{route('employees.show', ['employee' => $employee])}}"
                                       class="btn btn-primary">
                                        {{__('Show')}}
                                    </a>

                                    <a href="{{route('employees.edit',['employee' => $employee])}}"
                                       class="btn btn-primary">
                                        {{__('Edit')}}
                                    </a>
                                    <form action="{{route('employees.destroy',['employee' => $employee])}}" method="POST">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">

                                        <button type="submit" class="btn-primary btn mt-2">
                                            {{__('Delete')}}
                                        </button>
                                    </form>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <a href="{{route('employees.index')}}" class="btn btn-primary " style="margin-right: 20px;">{{__('Back')}}</a>

                            <h5>
                                {{__('Employees')}}
                            </h5>
                        </div>

                    </div>
                    <div class="card-body">
                        Name: {{$employee->name}} {{$employee->surname}}
                        <br>
                        Email: {{$employee->email}}
                        <br>
                        Phone: {{$employee->phone}}
                        <br>
                        Company: {{$employee->company->name}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/employees/update.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-center">
                            <a href="{{route('employees.index')}}" class="btn btn-primary " style="margin-right: 20px;">{{__('Back')}}</a>

                            <h5>
                                {{__('Employees')}}
                            </h5>
                        </div>

                    </div>
                    <div class="card-body">
                        <form action="{{route('employees.update',['employee' => $employee])}}" method="POST">
                            @csrf
                            <input type="hidden" name="_method" value="put"/>
                            <div class="form-group mb-2">
                                <label for="name">{{__('Name')}}</label>
                                <input type="text" class="form-control" name="name" id="name" required
                                       value="{{$employee->name}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="surname">{{__('Surname')}}</label>
                                <input type="text" class="form-control" name="surname" id="surname" required
                                       value="{{$employee->surname}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="email">{{__('Email')}}</label>
                                <input type="text" class="form-control" name="email" id="email"
                                       value="{{$employee->email}}">
                            </div>
                            <div class="form-group mb-2">
                                <label for="phone">{{__('Phone')}}</label>
                                <input type="tel" class="form-control" name="phone" id="phone"
                                       value="{{$employee->phone}}">
                            </div>

                            <div class="form-group mb-2">
                                <label for="company">{{__('Company')}}</label>
                                <select name="company_id" id="company" class="form-control" required>

                                    @foreach($companies as $company)
                                        <option value="{{$company->id}}"
                                                @if($employee->company_id == $company->id) selected @endif >{{$company->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group-mb-2">
                                <button type="submit" class="btn btn-primary">
                                    {{__('Submit')}}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body w-100">
                    <a href="{{route('companies.index')}}" class="btn btn-primary">
                        {{__('Companies')}}
                    </a>
                    <br>
                    <a href="{{route('employees.index')}}" class="btn btn-primary mt-2 mb-2">
                        {{__('Employees')}}
                    </a>
                    <br>


                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif


                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>